import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import TextField from '@material-ui/core/TextField';
import { Form, Formik, useFormik } from 'formik';
import * as yup from 'yup';
import Button from '@material-ui/core/Button';
import Swal from 'sweetalert2';
import withReactContent from 'sweetalert2-react-content'

export default function Home() {

  const formik = useFormik({
    initialValues: {
      number: ''
    },
    validationSchema: yup.object({
      number: yup.number().typeError('Value is required').required('Value is required')
    }),
    onSubmit: (values: { number: number | string }, actions) => {
      const MySwal = withReactContent(Swal)
      MySwal.fire({
        title: 'Are you ready?',
        html: <span>The number of questions in the quiz will be:<br />
          <span style={{ fontSize: '40px', margin: '5px', fontWeight: 'bold' }}>{values.number}</span></span>,
        icon: 'question',
        showCancelButton: true,
        confirmButtonColor: '#28a745',
        cancelButtonColor: '#d33',
        confirmButtonText: 'START!',
        cancelButtonText: 'CANCEL'
      }).then((result) => {
        if (result.isConfirmed) {

        } else {
          actions.resetForm({ values: { number: '' } })
        }
      })
      console.log(values)
    },
  });

  return (
    <div>
      <Head>
        <title>Wa Project - Front-end dev challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.input_div}>
        <div>
          <h1>General knowledge quiz</h1>
          <form autoComplete="off" onSubmit={formik.handleSubmit}>
            <TextField
              type="number"
              name="number"
              label="Number of questions"
              variant="outlined"
              fullWidth
              value={formik.values.number}
              onChange={formik.handleChange}
              error={formik.touched.number && Boolean(formik.errors.number)}
              helperText={formik.errors.number ? formik.errors.number : 'Enter the number of questions.'}
              placeholder="Ex. 5"
              size="small" />
            <Button type="submit" variant="contained" color="primary" size="small" fullWidth >SEND</Button>
          </form>
        </div>
      </div>

    </div>
  )
}
